# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      go:
        patterns:
          - "*"
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      frontend:
        patterns:
          - "*"
    labels:
      - dependencies
      - frontend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - ci
