package vrchatapi

import "strings"

// WrappedBlobMagic is the prefix the frontend prepends to base64-encoded (nonce + ciphertext).
// Its presence distinguishes an AES-GCM wrapped blob from a legacy plaintext token.
// Nonce must be 12 random bytes generated by crypto.getRandomValues – counter, fixed, or
// time-derived values are prohibited to avoid AES-GCM key-stream exposure.
const WrappedBlobMagic = "VRCTWKV1:"

// IsWrappedBlob reports whether s is a Web-Crypto-wrapped credential blob.
// Returns false for legacy plaintext tokens that predate Phase-B migration.
func IsWrappedBlob(s string) bool {
	return strings.HasPrefix(s, WrappedBlobMagic)
}
